FROM python:3.9.0-slim-buster as base
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY . /usr/src/app
RUN pip install --upgrade pip
RUN pip install -r build-requirements.txt
RUN pip install -r requirements.txt
RUN python setup.py install
RUN make try

FROM python:3.9.0-slim-buster
RUN mkdir -p /usr/src/app
COPY --from=base /usr/src/app/dist/* /usr/src/app/dist

WORKDIR /usr/src/app/dist/__main__

EXPOSE 8000

ENTRYPOINT ["./__main__"]
