version: '3'
services:
  some-rabbitmq:
    image: rabbitmq:3-management-alpine
    hostname: rabbit-host
    restart: unless-stopped
    ports:
     - "32779:4369"
     - "32778:5671"
     - "32777:5672"
     - "32776:15671"
     - "32775:15672"
  python-consumer:
    build:
      context: ../../src/python-consumer
      dockerfile: ../../src/python-consumer/Dockerfile
    volumes:
      - ~/phoneme:/local_data